//DOM, ACCEDE A LOS ELEMENTOS DEL HTML COMO UN H1 O LO QUE FUERE, EN ESTE CASO VOY A ENTRAR A UN H1//
//ACCEDO AL H1 Y CON EL TEXTCONTENT ACCEDO A LO DE ADENTRO Y SE LO CAMBIO//

document.querySelector("h1").textContent= "Texto desde js"